### ISSUE TITLE
error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:' [self.webView stringByEvaluatingJavaScriptFromString:jsCallBack]; 

### ISSUE THREAD

**Issue by nddeveloper** [raix/push#207]
Meteor 1.2 works fine

Meteor 1.3 Update gives error

I have used raix:push plugin in meteor project. It works fine in meteor 1.2 but in meteor 1.3 it gives error when compiling code in xcode. But it works fine in android.

.meteor/local/cordova-build/platforms/ios/meteor1.3/Plugins/com.phonegap.plugins.PushPlugin/PushPlugin.m:274:23: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
[self.webView stringByEvaluatingJavaScriptFromString:jsCallBack];

**Comment by raix** [comment]
can you give `3.0.3-rc.2` a go? it uses the latest cordova plugin,
the json config should still work - but the cordova plugin requires a setting in mobile-config.js https://github.com/raix/push/tree/fix-device-dependency-deprecate-json-format#config

**Comment by lorensr** [comment]
Thanks @raix! The linked readme says `  SENDER_ID: 12341234`. Looks like it needs to be a string `"12341234"`.

**Comment by raix** [comment]
bumped to `3.0.3-rc.3` - @lorensr have you tested both? *(the android config dictionary seems to be using string - but not sure how strict cordova is in handling this)*

**Comment by lorensr** [comment]
Oh, no
